"""updated db

Revision ID: 21f1770a07d6
Revises: 8fd40a4047a0
Create Date: 2025-12-08 18:03:57.771792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21f1770a07d6'
down_revision = '8fd40a4047a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ad_content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('advertiser_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['advertiser_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ad_content', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('advertiser_id')

    # ### end Alembic commands ###
