"""Added stats

Revision ID: 402ceef9adfc
Revises: dcb02e9c31f6
Create Date: 2024-12-19 15:04:50.601635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '402ceef9adfc'
down_revision = 'dcb02e9c31f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('traffic_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('endpoint', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('visitor_ip', sa.String(length=45), nullable=True))
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('traffic_stats', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_column('visitor_ip')
        batch_op.drop_column('endpoint')

    # ### end Alembic commands ###
