"""comment replying

Revision ID: 946089fd8cdc
Revises: 
Create Date: 2026-02-24 18:14:34.107496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '946089fd8cdc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('comment_', 'comment', ['parent_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint('comment_', type_='foreignkey')
        batch_op.drop_column('parent_id')

    # ### end Alembic commands ###
