"""added sbscription,bulk mail,etc

Revision ID: ffba5a7d759b
Revises: 402ceef9adfc
Create Date: 2024-12-19 16:05:27.529638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffba5a7d759b'
down_revision = '402ceef9adfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('newsletter_subscriber',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('subscribed_on', sa.DateTime(), nullable=True),
    sa.Column('subscribed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('newsletter_subscriber', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_newsletter_subscriber_email'), ['email'], unique=True)

    op.create_table('announcement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('announcement')
    with op.batch_alter_table('newsletter_subscriber', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_newsletter_subscriber_email'))

    op.drop_table('newsletter_subscriber')
    # ### end Alembic commands ###
